AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'test/**/*'
    - 'config.ru'
    - 'Gemfile'
    - 'Rakefile'
    - 'app/channels/**/*'
    - 'app/jobs/**/*'
    - 'app/mailers/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

Lint/MissingSuper:
  Enabled: false
